### ISSUE TITLE
Store action data in persistent store

### ISSUE THREAD

**Issue by pghosh** [Data4Democracy/indivisible#3] opened 2017-02-28 02:12 UTC
This task is to identify a simple backend solution and define structure to store the actions

**Comment by sgreene** [comment] 2017-03-11 03:24
Is this a duplicate of #13 ?

**Comment by pghosh** [comment] 2017-03-11 05:04
This one is to identify the backend we want to use. Like if it is mongo vs dynamo or something. Juts had a quick investigate pro/cons kind

**Comment by sgreene** [comment] 2017-03-11 05:09
I see. In one of the posts on slack I saw that dynamo was the chosen db. Great db but one huge con imo is that it requires an AWS account to actually use. There is a downloadable version, but it still requires an AWS account to use I think.

**Comment by pghosh** [comment] 2017-03-11 05:23
there is another issue that we can't change indexes on fly. I am leaning towards mongo but this will be a good place to things about pros and cons!

**Closed as completed** 2017-03-28 00:46 UTC
Labels: backend
